name: Example Request
description: Request and example of wandb
title: "[Request]: "
labels: ["library-integration", "wandb-feature", "other"]
assignees:
  - tcapelle
  - scottire 
body:
  - type: markdown
    attributes:
      value: |
        Hello, are you trying to find something that is missing in the examples/documentation? Do you want to propose an example? Please tell us more about!
        - You may find what you are looking for in our [forums](https://community.wandb.ai)
        - Or ping us on [twitter](https://twitter.com/weights_biases)
  - type: textarea
    id: request
    attributes:
      label: What is about?
      description: Tell us about the example/code you are looking for
      placeholder: Tell us what you see!
      value: "Please tell us more..."
    validations:
      required: true